import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/reports">Reports</Link>
        </li>
        <li>
          <Link to="/reportviewtwo">ReportViewTwo</Link>
        </li>
        <li>
          <Link to="/reportview">ReportView</Link>
        </li>
        <li>
          <Link to="/reportviewone">ReportViewOne</Link>
        </li>
        <li>
          <Link to="/drivers">Drivers</Link>
        </li>
        <li>
          <Link to="/driversone">DriversOne</Link>
        </li>
        <li>
          <Link to="/vehicle">Vehicle</Link>
        </li>
        <li>
          <Link to="/map">Map</Link>
        </li>
        <li>
          <Link to="/conversation">Conversation</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
